### PR TITLE
corrected colour key labels

### PR DESCRIPTION
**Pull request by MaPaw**
The numbers on the colour key sometimes look odd when not all levels
have labels.  I have tried to improve this by accounting for the
increment in the calculation of the required space.

### CODE REVIEW

**Comment by MaPaw** [comment]
please ignore the first two commits

**Comment by karlmsmith** [comment]
Hi,

Thank you for contributing!

Can you provide an example where you are seeing the issue in the original code but is improved in the updated code?  We are trying some more plots, but the plots in our standard tests do not show any differences in my testing of the updated code.  But if we can come up with an example showing the improvements, I would like to include that in our standard tests.

Best regards,
Karl Smith

**Comment by MaPaw** [comment]
Hi Karl,

here are a jnl script, a datafile and two plots showing the difference.  In the file fe_orig.pdf, the colur key labels have two extra zeros, one of which is cut off.  In the file fe_mode.pdf (with the modified key.F), the key labels look as I wanted them.

Best regards,
Markus


--
Markus Pahlow			Tel.:	+49-431-600-4027
GEOMAR				Fax:	+49-431-600-4469
Düsternbrooker Weg 20		E-mail: mpahlow@geomar.de <mailto:mpahlow@geomar.de>
24105 Kiel, Germany

**Comment by karlmsmith** [comment]
Hi Marcus,

I am not seeing the journal script anywhere.  Did you commit it to your repository or was it an attachment that disappeared somewhere?  If you want to commit, it put it under the bench subdirectory.  If you want to just send it to me, the email address is karl.smith@noaa.gov

Thanks,
Karl

**Comment by karlmsmith** [comment]
Hi Markus,

I made the updates in the code (minimizing the number of changes to the essential ones) in Ferret, then brought those updates into PyFerret.  So you should now see your changes (and associated with you) in master under both Ferret and PyFerret.  So I am closing this pull request.

Thank you for the contribution!

Best regards,
Karl

**Pull request closed without merging**
